namespace BFF.API;

/// <summary>
/// Represents the correlation information between a frontend request and a saga
/// </summary>
public class CorrelationInfo
{
    /// <summary>
    /// The correlation ID generated by the BFF for the frontend
    /// </summary>
    public Guid CorrelationId { get; set; }
    
    /// <summary>
    /// The saga ID from the ingestion service
    /// </summary>
    public Guid SagaId { get; set; }
    
    /// <summary>
    /// The image ID being processed
    /// </summary>
    public Guid ImagenId { get; set; }
    
    /// <summary>
    /// When the correlation was created
    /// </summary>
    public DateTime CreatedAt { get; set; }
}
