// <auto-generated />
using System;
using Ingestion.Aplicacion.Anonimizacion.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ingestion.Aplicacion.Anonimizacion.Persistencia.Migrations
{
    [DbContext(typeof(AnonimizarDbContext))]
    partial class AnonimizarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ingestion.Aplicacion.Anonimizacion.Persistencia.Entidades.ImagenAnonimizadaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contraste")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionModalidad")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionRegionAnatomica")
                        .HasColumnType("text");

                    b.Property<string>("DetalleAnonimizacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Es3D")
                        .HasColumnType("boolean");

                    b.Property<string>("FaseEscaner")
                        .HasColumnType("text");

                    b.Property<Guid>("ImagenId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreModalidad")
                        .HasColumnType("text");

                    b.Property<string>("RegionAnatomica")
                        .HasColumnType("text");

                    b.Property<string>("Resolucion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UbicacionImagen")
                        .HasColumnType("text");

                    b.Property<string>("UbicacionImagenProcesada")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnonimizacionImagenes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
