// <auto-generated />
using System;
using Ingestion.Aplicacion.Metadata.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ingestion.Aplicacion.Metadata.Persistencia.Migraciones
{
    [DbContext(typeof(MetadataDbContext))]
    partial class MetadataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ingestion.Aplicacion.Metadata.Persistencia.Entidades.MetadataImagenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CondicionesPrevias")
                        .HasColumnType("text");

                    b.Property<string>("Contraste")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionModalidad")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionPatologia")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionRegionAnatomica")
                        .HasColumnType("text");

                    b.Property<bool>("Diabetico")
                        .HasColumnType("boolean");

                    b.Property<bool>("Es3D")
                        .HasColumnType("boolean");

                    b.Property<string>("EtapaContextoProcesal")
                        .HasColumnType("text");

                    b.Property<string>("Etnicidad")
                        .HasColumnType("text");

                    b.Property<string>("FaseEscaner")
                        .HasColumnType("text");

                    b.Property<bool>("Fumador")
                        .HasColumnType("boolean");

                    b.Property<string>("GrupoEdad")
                        .HasColumnType("text");

                    b.Property<Guid>("ImagenId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreModalidad")
                        .HasColumnType("text");

                    b.Property<string>("RegionAnatomica")
                        .HasColumnType("text");

                    b.Property<string>("Resolucion")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("Sintomas")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoAmbiente")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<string>("VersionServicio")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImagenId")
                        .IsUnique();

                    b.ToTable("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
