// <auto-generated />
using System;
using Consulta.Aplicacion.Demografia.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consulta.Aplicacion.Demografia.Persistencia.Migrations
{
    [DbContext(typeof(ImagenDemografiaDbContext))]
    partial class ImagenDemografiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consulta.Aplicacion.Demografia.Persistencia.Entidades.ImagenDemografiaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Etnicidad")
                        .HasColumnType("text");

                    b.Property<string>("GrupoEdad")
                        .HasColumnType("text");

                    b.Property<Guid>("ImagenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Etnicidad");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Etnicidad"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Etnicidad"), new[] { "gin_trgm_ops" });

                    b.HasIndex("GrupoEdad");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("GrupoEdad"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("GrupoEdad"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ImagenId")
                        .IsUnique();

                    b.HasIndex("Sexo");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Sexo"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Sexo"), new[] { "gin_trgm_ops" });

                    b.ToTable("ImagenesDemograficas");
                });
#pragma warning restore 612, 618
        }
    }
}
