@startuml

skinparam componentStyle uml2

package comandos {
	package "'ComandosConsulta' Aggregate" <<Rectangle>> {
		class ImagenConsultaDemografiaRequestCommand <<(E,DarkSeaGreen) Entity>> {
			String sagaId
			Demografia filter
		}
		class ImagenConsultaModalidadRequestCommand <<(E,DarkSeaGreen) Entity>> {
			String sagaId
			TipoImagen filter
		}
		class ImagenConsultaDataRequestCommand <<(E,DarkSeaGreen) Entity>> {
			String sagaId
			List<String> imagenIds
		}
		class TipoImagen <<(E,DarkSeaGreen) Entity>> {
			Modalidad modalidad
			RegionAnatomica regionAnatomica
			Patologia patologia
		}
		class Demografia <<(E,DarkSeaGreen) Entity>> {
			String grupoEdad
			String sexo
			String etnicidad
		}
	}
}
ImagenConsultaModalidadRequestCommand --> TipoImagen : filter
ImagenConsultaDemografiaRequestCommand --> Demografia : filter


@enduml
