@startuml

skinparam componentStyle uml2

package ambienteVirtual {
	package "'SeguridadAmbiente' Aggregate" <<Rectangle>> {
		class ControlAcceso <<(E,DarkSeaGreen) Entity>> {
			String tipoAmbiente
			String politicaSeguridad
			String nivelAislamiento
			String regionCloud
		}
		class Auditoria <<(E,DarkSeaGreen) Entity>> {
			String tipoOperacion
			Date timestamp
			String usuario
			String resultado
		}
		class ConfiguracionRed <<(E,DarkSeaGreen) Entity>> {
			String vpcConfig
			String firewallRules
			String encryptionKeys
		}
	}
}
legend left
  This bounded context implements the subdomain 'GestionClientes', which contains the following entities:
   - Cliente
  This bounded context implements the subdomain 'AmbienteVirtual', which contains the following entities:
   - Ambiente
  This bounded context implements the subdomain 'Atribucion', which contains the following entities:
   - UsoImagen
   - CompensacionProveedor
end legend


@enduml
