@startuml

skinparam componentStyle uml2

package "'Almacenamiento' Generic Subdomain" <<Rectangle>> {
	class Contenedor <<(E,DarkSeaGreen) Entity>> {
		String id
		String proveedorId
		String region
		String tipo
		Double capacidad
	}
}
legend left
  This subdomain is part of the 'Procesamiento' domain.

  Gestionar el almacenamiento seguro y aislado de datos por proveedor
end legend


@enduml
