@startuml

skinparam componentStyle uml2

package sagas {
	package "'ImagenConsultaSaga' Aggregate" <<Rectangle>> {
		class ImagenConsultaSagaState <<(E,DarkSeaGreen) Entity>> {
			String sagaId
			String status
			Date createdAt
			Date completedAt
			String errorMessage
			List<String> demografiaResults
			List<String> modalidadResults
			List<String> intersectedIds
			List<ImagenMedica> finalResults
			Demografia demografiaFilter
			TipoImagen tipoImagenFilter
		}
	}
}


@enduml
