// <auto-generated />
using System;
using Consulta.Aplicacion.Modalidad.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consulta.Aplicacion.Modalidad.Persistencia.Migrations
{
    [DbContext(typeof(ImagenModalidadDbContext))]
    partial class ImagenModalidadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consulta.Aplicacion.Modalidad.Persistencia.Entidades.ImagenModalidadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImagenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("RegionAnatomica")
                        .HasColumnType("text");

                    b.Property<string>("RegionDescripcion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Descripcion"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Descripcion"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ImagenId")
                        .IsUnique();

                    b.HasIndex("Nombre");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nombre"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Nombre"), new[] { "gin_trgm_ops" });

                    b.HasIndex("RegionAnatomica");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RegionAnatomica"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("RegionAnatomica"), new[] { "gin_trgm_ops" });

                    b.HasIndex("RegionDescripcion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RegionDescripcion"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("RegionDescripcion"), new[] { "gin_trgm_ops" });

                    b.ToTable("ImagenesModalidad");
                });
#pragma warning restore 612, 618
        }
    }
}
