apiVersion: v1
kind: Pod
metadata:
  name: bff-service
  labels:
    app: bff-service
spec:
  containers:
  - name: bff-service
    image: saludtech/bff-service:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    env:
    - name: MessageBroker__Host
      value: "broker"
    - name: MessageBroker__Port
      value: "6650"
    - name: Redis__ConnectionString
      value: "redis:6379"
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
      requests:
        memory: "128Mi"
        cpu: "100m"
