apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  selector:
    app: bff-service
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  # You can specify a fixed port if needed
  # nodePort: 30080
