apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: bookie
  name: bookie
spec:
  containers:
    - args:
        - bash
        - -c
        - bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie
      env:
        - name: BOOKIE_MEM
          value: -Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
        - name: advertisedAddress
          value: bookie
        - name: clusterName
          value: cluster-a
        - name: metadataServiceUri
          value: metadata-store:zk:zookeeper:2181
        - name: zkServers
          value: zookeeper:2181
      image: apachepulsar/pulsar:latest
      name: bookie
      ports:
        - containerPort: 3181
          protocol: TCP
        - containerPort: 4181
          protocol: TCP
  restartPolicy: OnFailure
