apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: bookie
  name: bookie
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookie
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: bookie
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /pulsar/data/bookkeeper && chmod -R 777 /pulsar/data/bookkeeper"]
          volumeMounts:
            - mountPath: /pulsar/data/bookkeeper
              name: bookie-data
      containers:
        - args:
            - bash
            - -c
            - bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie
          env:
            - name: BOOKIE_MEM
              value: -Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
            - name: advertisedAddress
              value: bookie
            - name: clusterName
              value: cluster-a
            - name: metadataServiceUri
              value: metadata-store:zk:zookeeper:2181
            - name: zkServers
              value: zookeeper:2181
          image: apachepulsar/pulsar:latest
          name: bookie
          ports:
            - containerPort: 3181
              protocol: TCP
            - containerPort: 4181
              protocol: TCP
          volumeMounts:
            - mountPath: /pulsar/data/bookkeeper
              name: bookie-data
      restartPolicy: Always
      volumes:
        - name: bookie-data
          persistentVolumeClaim:
            claimName: bookie-data
