apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookie-data
  labels:
    io.kompose.service: bookie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
