apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consulta-service
  name: consulta-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consulta-service
  template:
    metadata:
      labels:
        io.kompose.service: consulta-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DataWarehouse__Host
              value: http://ingestion-service/api/imagenes/ids
            - name: MessageBroker__Host
              value: broker
            - name: MessageBroker__Port
              value: "6650"
            - name: MessageBroker__SubscriptionType
              value: "Shared"
            - name: Redis__ConnectionString
              value: redis:6379
            - name: ServiciosFiltro__Demografia
              value: http://demografia-service/api/demografia/buscar
            - name: ServiciosFiltro__Modalidad
              value: http://modalidad-service/api/modalidad/buscar
            - name: DOTNET_HostOptions__BackgroundServiceExceptionBehavior
              value: Ignore
          image: northamerica-northeast2-docker.pkg.dev/miso-nomonoliticas/no-monoliticas/consulta-service:latest
          name: consulta-service
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["NET_BIND_SERVICE"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
