apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: consulta-service
  name: consulta-service
spec:
  containers:
    - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DataWarehouse__Host
          value: http://ingestion-service/api/imagenes/ids
        - name: MessageBroker__Host
          value: broker
        - name: MessageBroker__Port
          value: "6650"
        - name: Redis__ConnectionString
          value: redis:6379
        - name: ServiciosFiltro__Demografia
          value: http://demografia-service/api/demografia/buscar
        - name: ServiciosFiltro__Modalidad
          value: http://modalidad-service/api/modalidad/buscar
      image: northamerica-northeast2-docker.pkg.dev/miso-nomonoliticas/no-monoliticas/consulta-service:latest
      name: consulta-service
      ports:
        - containerPort: 80
          protocol: TCP
  restartPolicy: OnFailure
