apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ingestion-service
  name: ingestion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ingestion-service
  template:
    metadata:
      labels:
        io.kompose.service: ingestion-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Host=10.114.240.3;Database=SaludTechIngestionDb;Username=postgres;Password=postgres;SslMode=Disable
            - name: MessageBroker__Host
              value: broker
            - name: MessageBroker__Port
              value: "6650"
            - name: Redis__ConnectionString
              value: redis:6379
            - name: DOTNET_HostOptions__BackgroundServiceExceptionBehavior
              value: Ignore
          image: northamerica-northeast2-docker.pkg.dev/miso-nomonoliticas/no-monoliticas/ingestion-service:latest
          name: ingestion-service
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["NET_BIND_SERVICE"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
