apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: metadata-service
  name: metadata-service
spec:
  containers:
    - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__DefaultConnection
          value: Host=10.114.240.3;Database=SaludTechMetadataDb;Username=postgres;Password=postgres;SslMode=Disable
        - name: MessageBroker__Host
          value: broker
        - name: MessageBroker__Port
          value: "6650"
      image: northamerica-northeast2-docker.pkg.dev/miso-nomonoliticas/no-monoliticas/metadata-service:latest
      name: metadata-service
      ports:
        - containerPort: 80
          protocol: TCP
  restartPolicy: OnFailure
