apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: metadata-service
  name: metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metadata-service
  template:
    metadata:
      labels:
        io.kompose.service: metadata-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Host=10.114.240.3;Database=SaludTechMetadataDb;Username=postgres;Password=postgres;SslMode=Disable
            - name: MessageBroker__Host
              value: broker
            - name: MessageBroker__Port
              value: "6650"
            - name: MessageBroker__SubscriptionType
              value: "Shared"
            - name: DOTNET_HostOptions__BackgroundServiceExceptionBehavior
              value: Ignore
            # Añadir configuración de logging
            - name: Logging__LogLevel__Default
              value: "Information"
            - name: Logging__LogLevel__Microsoft
              value: "Warning"
            - name: Logging__LogLevel__Ingestion
              value: "Information"
          image: northamerica-northeast2-docker.pkg.dev/miso-nomonoliticas/no-monoliticas/metadata-service:latest
          name: metadata-service
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["NET_BIND_SERVICE"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
