apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
  labels:
    io.kompose.service: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
