apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://loki:3100/loki/api/v1/push
    
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_io_kompose_service]
            regex: (ingestion-service|anonimizacion-service|metadata-service)
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
        pipeline_stages:
          - regex:
              expression: '.*SAGA_EVENT.*'
              action: keep
          - json:
              expressions:
                SagaEvent: SagaEvent
          - json:
              source: SagaEvent
              expressions:
                sagaId: sagaId
                sagaType: sagaType
                eventType: eventType
                timestamp: timestamp
          - labels:
              sagaId:
              sagaType:
              eventType:
